### ISSUE TITLE
"Microsoft 365 Assessment tool did not start timely"

### ISSUE THREAD

**Issue by gw3437** [pnp/pnpassessment#19]
Here is what I get when trying to analyze my workflows:
Connecting Microsoft 365 Assessment on port 25010...
No running Microsoft 365 Assessment found, starting one...
Unhandled exception: System.Exception: Microsoft 365 Assessment tool did not start timely
   at PnP.Scanning.Process.Services.ScannerManager.WaitForScannerToBeUpAsync()
   at PnP.Scanning.Process.Services.ScannerManager.LaunchScannerAsync()
   at PnP.Scanning.Process.Services.ScannerManager.GetScannerClientAsync()
   at PnP.Scanning.Process.Commands.StartCommandHandler.<>c__DisplayClass19_0.<<HandleStartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in /_/src/Spectre.Console/Live/Status/Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in /_/src/Spectre.Console/Live/Status/Status.cs:line 77
   at PnP.Scanning.Process.Commands.StartCommandHandler.HandleStartAsync(StartOptions arguments)
   at PnP.Scanning.Process.Commands.StartCommandHandler.<Create>b__18_0(StartOptions arguments)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass26_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__23_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__8_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__7_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseExceptionHandler>b__0>d.MoveNext()

The log file shows this. 
2023-04-19 12:23:55.787 -05:00 [INF] Starting Microsoft 365 Assessment on port 25010
2023-04-19 12:23:56.171 -05:00 [INF] Started Microsoft 365 Assessment on port 25010
2023-04-19 12:23:56.241 -05:00 [INF] User profile is available. Using 'C:\Users\<username>\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2023-04-19 12:23:56.602 -05:00 [INF] Now listening on: http://localhost:25010
2023-04-19 12:23:56.608 -05:00 [INF] Application started. Press Ctrl+C to shut down.
2023-04-19 12:23:56.609 -05:00 [INF] Hosting environment: Production
2023-04-19 12:23:56.609 -05:00 [INF] Content root path: C:\microsoft365assessment

Any ideas?

**Comment by jansenbe** [comment]
@gw3437 : the error indicates that the "server" part of the assessment tool did not start timely. The server part is an ASP.NET web server (kestrel) running on port 25010. If for some reason there's something else is already using that port then the server can't start. Can you check the following:

- Verify all `microsoft365-assessment.exe` processes are gone and try again (this can rule a rogue assessment process that somehow blocks things)
- If that does not work please try using a different port, see https://pnp.github.io/pnpassessment/using-the-assessment-tool/configuration.html#using-a-different-port-than-25010 for how to do that
- If that does not work, can you see if you can put the `microsoft365-assessment.exe` in a folder that's excluded from your AV scanning...trying to rule out it's impacting things
- Trying on another machine might help as well? What OS are you using to run the tool?

**Comment by jansenbe** [comment]
@gw3437 : did above help get you unblocked?

**Comment by jansenbe** [comment]
@gw3437 : I'm closing this issue as there was not feedback anymore. In case the problem still persists please re-open and let me know how the recommended steps turned out.
