### ISSUE TITLE
Assessment job not started due to error: SharePoint Rest service exception

### ISSUE THREAD

**Issue by hsantuyo** [pnp/pnpassessment#20]
Hi,

Any idea for this issue? we've configured the required steps to run the tools
1. [Download the tool](https://pnp.github.io/pnpassessment/using-the-assessment-tool/download.html)
2. [Configure authentication](https://pnp.github.io/pnpassessment/using-the-assessment-tool/setupauth.html)
3. [Run an assessment](https://pnp.github.io/pnpassessment/using-the-assessment-tool/assess.html)

![image](https://user-images.githubusercontent.com/131945314/234775433-14e5b2f8-d8dc-493d-80fa-46e1793bae6a.png)

But we've got error saying SharePoint Rest service exception

Could you please help me for this error or if I missed anything?

Thanks,

**Comment by jansenbe** [comment]
@hsantuyo : can you check if there's anything meaningful in the logs? The rest exception means that a call to SharePoint failed, most likely due to permission issues. If that's not providing any details then you could also do a Fiddler trace to see if that shows the failing call.

**Comment by hsantuyo** [comment]
@jansenbe 

Thank you for the response. We tried account with Global Admin access but still the same.

Below is the logs.

2023-05-04 13:54:47.502 +10:00 [INF] Starting Microsoft 365 Assessment
2023-05-04 13:54:47.505 +10:00 [INF] Building list of site collections to assess
2023-05-04 13:54:47.505 +10:00 [INF] Building list of site collections: using tenant scope
2023-05-04 13:54:47.646 +10:00 [INF] Start processing HTTP request GET "https://mychemist.sharepoint.com/_api/Web?$select=Id%2cUrl%2cRegionalSettings%2f*%2cRegionalSettings%2fDateFormat&$expand=RegionalSettings%2cRegionalSettings%2fTimeZone"
2023-05-04 13:54:47.647 +10:00 [INF] Sending HTTP request GET "https://mychemist.sharepoint.com/_api/Web?$select=Id%2cUrl%2cRegionalSettings%2f*%2cRegionalSettings%2fDateFormat&$expand=RegionalSettings%2cRegionalSettings%2fTimeZone"
2023-05-04 13:54:47.757 +10:00 [INF] Received HTTP response headers after 110.5457ms - 401
2023-05-04 13:54:47.757 +10:00 [INF] End processing HTTP request after 110.9221ms - 401
2023-05-04 13:54:47.758 +10:00 [ERR] Error starting assessment job: SharePoint Rest service exception
HttpResponseCode: 401
Code: 
Message: {"error_description":"ID3035: The request was not valid or is malformed."}
ClientRequestId: 2c71afa0-90a2-2000-3b7c-de27d818839f

PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Services.PnPContextFactory.InitializeContextAsync(PnPContext context, PnPContextOptions options)
   at PnP.Core.Services.PnPContextFactory.CreateAsync(Uri url, IAuthenticationProvider authenticationProvider, CancellationToken cancellationToken, PnPContextOptions options)
   at PnP.Core.Services.PnPContextFactory.CreateAsync(Uri url, IAuthenticationProvider authenticationProvider, PnPContextOptions options)
   at PnP.Scanning.Core.Services.SiteEnumerationManager.EnumerateSiteCollectionsToScanAsync(StartRequest start, AuthenticationManager authenticationManager, Action`1 feedback)
   at PnP.Scanning.Core.Services.Scanner.Start(StartRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context)
2023-05-04 13:54:47.759 +10:00 [INF] Executed endpoint 'gRPC - /PnP.Scanning.Core.Services.PnPScanner/Start'
2023-05-04 13:54:47.759 +10:00 [INF] Request finished HTTP/2 POST http://localhost:25010/PnP.Scanning.Core.Services.PnPScanner/Start application/grpc - - 200 - application/grpc 257.4559ms

Could you please review what possible cause. Thank you

**Comment by jansenbe** [comment]
Hey @hsantuyo , error `ID3035: The request was not valid or is malformed` indicates it's a permission issue, meaning the access token is not valid. Can you cross check that you've done an admin grant of the Graph `Sites.Read.All` and SharePoint `Sites.Manage.All` permissions (https://pnp.github.io/pnpassessment/workflow/requirements.html#permission-requirements) for the app (`eeaacc52...`) you're using. See https://pnp.github.io/pnpassessment/using-the-assessment-tool/setupauth.html#creating-an-azure-ad-application-using-the-azure-ad-portal to learn more on the manual Azure AD app configuration steps.

When retesting, also ensure all `microsoft365-assessment.exe` processes have been stopped before retrying.

**Comment by jansenbe** [comment]
@hsantuyo : are you unblocked, can this issue be closed?

**Comment by hsantuyo** [comment]
Hello Jansebe,

After reviewing all permissions required, I'm able to run the assessment without issue. Thank you for you assistance.

You can close this issue.

**Comment by hrithikiguttedar** [comment]
Hello @jansenbe 
the assessment status got stuck in Pausing status, could you please assist me.

![image](https://github.com/user-attachments/assets/8dacb7d6-4389-4e7e-be8a-059d1cac4bd1)

**Comment by jansenbe** [comment]
just kill all the microsoft365assessment.exe processes and then restart the failed assessment. Also, please ensure you run these long running assessments on a machine that can stay running. Pausing can work but it's easier to just let it run

**Comment by hrithikiguttedar** [comment]
post report has extracted, the workflow csv file I am able to see only headers without data
![image](https://github.com/user-attachments/assets/3ebbc479-5877-4978-83bb-f016d8a6650a)
