### ISSUE TITLE
Assessment job not started due to error: System.DllNotFoundException: Dll was not found.

### ISSUE THREAD

**Issue by carry2web** [pnp/pnpassessment#46]
microsoft assessment tool job after scan fails to start job due to missing SQL Lite DLL
You are using the latest version 1.7.0

Can you instruct how to get the missing DLL or troubleshoot?

Part of logfile below:
2024-03-21 23:00:42.171 +01:00 [INF] Assessment scope defined: 21838 site collections will be assessed
2024-03-21 23:00:42.177 +01:00 [INF] Starting the assessment job
2024-03-21 23:00:42.177 +01:00 [INF] Assessment id is "43317fc9-ae70-405f-9832-3ba7238eef02"
2024-03-21 23:00:42.876 +01:00 [ERR] Error starting assessment job: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Dll was not found.
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at PnP.Scanning.Core.Storage.StorageManager.LaunchNewScanAsync(Guid scanId, StartRequest start, List`1 siteCollectionList)
   at PnP.Scanning.Core.Services.ScanManager.StartScanAsync(StartRequest start, AuthenticationManager authenticationManager, List`1 siteCollectionList)
   at PnP.Scanning.Core.Services.Scanner.Start(StartRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context)

**Comment by jansenbe** [comment]
@carry2web : that's a very weird error...the DLLs and minimal .NET runtime are "integrated" in the .exe by the .NET compiler. At runtime .NET will unpack what's needed and execute the code. Could it be that there's some Antivirus/security software that intercepts things?

**Comment by carry2web** [comment]
I suspect my enterprise workplace has indeed some security interception. I have run an earlier version of the tool before. Will try on different environment and let you know.

**Comment by jansenbe** [comment]
Earlier versions of the tool used exactly the same model and the same .NET version, so if it worked before I'm guessing that your machine got more locked down

**Comment by jansenbe** [comment]
@carry2web : did you manage to get the assessment working?
