### ISSUE TITLE
Issue : Microsoft Graph service exception

### ISSUE THREAD

**Issue by NGseb** [pnp/pnpassessment#61]
Hello, 
I have the following errors with the latest version. Any idea?

```
PS C:\Users\XXXXXXX\Documents\M365 Assesment tool> C:\Users\XXXXXXX\Documents\M365 Assesment tool\launch.ps1
Version check...

You are using the latest version 1.9.0

Connecting Microsoft 365 Assessment on port 25010...
Starting Microsoft 365 Assessment...
OK

Initializing authentication
Starting the Microsoft 365 Assessment
Microsoft 365 Assessment authentication initialized
Enumerated ZZZZZ site collections for tenant YYYYY.sharepoint.com
Sites to assess are defined
**Assessment job not started due to error: Microsoft Graph service exception**
```
.\microsoft365-assessment_v1.9.0.exe list
Version check...

You are using the latest version 1.9.0

Connecting Microsoft 365 Assessment on port 25010...
OK
ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿
³ Id            ³ Mode      ³ Status ³   Progress    ³ Started at   ³ Ended at ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´
³ 7a5275bc-ABCD³ AddInsACS ³ Queued ³ 0/ZZZZZ (0%) ³ 19/06/2024   ³          ³
³ -ABCD-ABCD-c5 ³           ³        ³               ³ 10:05:56     ³          ³
³ ee3a6b1bb7    ³           ³        ³               ³              ³          ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÙ

.\microsoft365-assessment_v1.9.0.exe status
Version check...

You are using the latest version 1.9.0

Connecting Microsoft 365 Assessment on port 25010...
OK

Live running Microsoft 365 Assessment status. Press ESC to exit

.\microsoft365-assessment_v1.9.0.exe : Unhandled exception: System.IO.IOException: The handle is invalid.
At line:1 char:1
+ .\microsoft365-assessment_v1.9.0.exe status
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...dle is invalid.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at Spectre.Console.LegacyConsoleCursor.Show(Boolean show) in /_/src/Spectre.Console/Internal/Backends/Legacy/LegacyConsoleCursor.cs:line 7
   at Spectre.Console.CursorExtensions.Hide(IAnsiConsoleCursor cursor) in /_/src/Spectre.Console/Extensions/CursorExtensions.cs:line 33
   at Spectre.Console.LiveDisplayRenderer.Started() in /_/src/Spectre.Console/Live/LiveDisplayRenderer.cs:line 16
   at Spectre.Console.LiveDisplay.<>c__DisplayClass18_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/LiveDisplay.cs:line 104
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.LiveDisplay.StartAsync[T](Func`2 func) in /_/src/Spectre.Console/Live/LiveDisplay.cs:line 98
   at Spectre.Console.LiveDisplay.StartAsync(Func`2 func) in /_/src/Spectre.Console/Live/LiveDisplay.cs:line 78
   at PnP.Scanning.Process.Commands.StatusCommandHandler.HandleStatusAsync()
   at PnP.Scanning.Process.Commands.StatusCommandHandler.<Create>b__2_0()
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by jansenbe** [comment]
@NGseb : you talk about a graph exception, you can learn more from the generated log file but typically this because of missing permissions. See https://pnp.github.io/pnpassessment/addinsacs/requirements.html#permission-requirements for the permissions for the AddInsACS run, folks tend to overlook the need for Application.Read.All.

The other issues seem to be related the shell being used. Can you try to execute from a PS7 console

**Comment by NGseb** [comment]
thanks a lot, it worked with the permissions on the App :-)
